import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";


export const metadata: Metadata = {
  title: "platform-snippet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-50 min-h-screen">
        <div className="min-h-screen flex flex-col">
          <header className="bg-gray-900 text-white">
            <div className="container mx-auto px-4 py-4 flex justify-between items-center">
              <Link href="/" className="text-xl font-bold">
                CodeShare
              </Link>
              <nav className="space-x-4">
                <Link href="/snippets" className="hover:underline">
                  Snippets
                </Link>
                <Link href="/tags" className="hover:underline">
                  Tags
                </Link>
                <Link href="/profile" className="hover:underline">
                  Profile
                </Link>
              </nav>
            </div>
          </header>

          <main className="flex-1 container mx-auto px-4 py-6">{children}</main>

          <footer className="bg-gray-100 text-center py-4 border-t">
            <p className="text-sm text-gray-500">
              © {new Date().getFullYear()} CodeShare. All rights reserved.
            </p>
          </footer>
        </div>
      </body>
    </html>
  );
}
